#
#  lib/front_matter.py
#  Structured front-matter content for the copyright and usage pages.
#
#  The lemma repo ships with defaults matching the basic edition. The pro
#  build passes --front-matter <path.json> to override fields; unspecified
#  fields fall through to the defaults.
#
#  NOTE: Only structured fields are accepted here. Raw HTML from outside the
#  lemma repo is deliberately not supported so the HTML template and escaping
#  stay under lemma's control.
#

import json


# Defaults match the basic edition's current content. The pro build overrides
# these from lemma_pro/front_matter.json.
BASIC_DEFAULTS = {
    # edition_name is intentionally None by default so basic builds get
    # "Lemma Greek Basic Dictionary" and pro builds without a front-matter
    # override get "Lemma Greek Dictionary", both computed from the build
    # flavor in html_generator._default_edition_name().
    "edition_name": None,
    "tagline": (
        "A Greek-English dictionary built from English Wiktionary. "
        "Look up any Greek word while reading, inflected forms "
        "automatically redirect to their headword."
    ),
    "copyright": {
        "holder": "Francisco Riordan",
        "extra_lines": [],
    },
    "tools": [
        {
            "role": "Dictionary compiled by",
            "name": "Lemma",
            "url": "https://github.com/ciscoriordan/lemma",
            "suffix": ".",
        },
        {
            "role": "MOBI generated by",
            "name": "Kindling",
            "url": "https://github.com/ciscoriordan/kindling",
            "suffix": " by Francisco Riordan.",
        },
    ],
    "data_sources": [
        {
            "name": "Wiktionary",
            "url": "https://en.wiktionary.org/",
            "desc": (
                "dictionary content available under the "
                "<a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">"
                "Creative Commons Attribution-ShareAlike 4.0 International License</a>. "
                "Machine-readable data provided by "
                "<a href=\"https://kaikki.org/\">Kaikki.org</a>."
            ),
        },
        {
            "name": "Dilemma",
            "url": "https://github.com/ciscoriordan/dilemma",
            "desc": "Greek lemmatizer by Francisco Riordan (inflection data).",
        },
        {
            "name": "FrequencyWords",
            "url": "https://github.com/hermitdave/FrequencyWords",
            "desc": "word frequency data from the OpenSubtitles 2018 corpus, MIT License.",
        },
    ],
    "features": [
        "31,000+ headwords with 660,000+ inflected lookup forms",
        "Both monotonic and polytonic Greek supported",
        "Part of speech tags",
    ],
}


def _deep_merge(base, overrides):
    """Recursively merge dict overrides on top of base. Lists and scalars in
    overrides replace the corresponding value in base entirely; dicts merge
    key by key.
    """
    if not isinstance(overrides, dict) or not isinstance(base, dict):
        return overrides
    result = dict(base)
    for key, value in overrides.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def load_front_matter(path=None):
    """Return the front-matter dict for a build.

    If `path` is None, returns a deep copy of BASIC_DEFAULTS. Otherwise reads
    the JSON file at `path` and deep-merges it on top of BASIC_DEFAULTS.
    """
    base = json.loads(json.dumps(BASIC_DEFAULTS))  # deep copy via JSON roundtrip
    if path is None:
        return base
    with open(path, "r", encoding="utf-8") as f:
        overrides = json.load(f)
    if not isinstance(overrides, dict):
        raise ValueError(f"Front-matter file {path} must contain a JSON object")
    return _deep_merge(base, overrides)
